library(adventofcode2021)
input <- readLines(input_file(21))
player <- as.numeric(substring(input, nchar(input)))
deterministic_dice(player[1], player[2])
dirac_dice(player[1], player[2]) |> format(scientific = FALSE)
