library(adventofcode2021)
input <- c(read_origami(input_file(13)), n = 1)
sum(do.call(fold_paper, input))
input$n <- nrow(input[[2]])
folded <- do.call(fold_paper, input)
image(folded[, ncol(folded):1], col = c('white', '#f5c966'))
