name: R

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        r-version: ['3.6.3', '4.1.1']

    steps:
      - uses: actions/checkout@master
      - run: brew install ghostscript
      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-pandoc@v1
        with:
          pandoc-version: '2.7.3'
      - run: echo "# Test" | pandoc -t html
      - uses: r-lib/actions/setup-r-dependencies@v1
        with:
          extra-packages: rcmdcheck
      - uses: r-lib/actions/setup-tinytex@v1
      - run: tlmgr --version
      - uses: r-lib/actions/check-r-package@v1
        with:
          build_args: c('--compact-vignettes=gs+qpdf')
